apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-onlyjava #The name of the Kubernetes Deployment to be created in the Kubernetes cluster
  labels:
    app: hello-onlyjava
spec:
  replicas: 2 #The number of pods to be created in the Kubernetes cluster for the application container
  selector:
    matchLabels:
      app: hello-onlyjava
  template:
    metadata:
      labels:
        app: hello-onlyjava
    spec:
      containers:
      - name: hello-onlyjava #The name of the application container
        image: merxxaz/hello-world-onlyjava:v1.0.0 #The Docker image for building the application container
        ports:
        - containerPort: 8002 #The port for the application container
