apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-service #The name of the Kubernetes Deployment to be created in the Kubernetes cluster
  labels:
    app: python-app-service
spec:
  replicas: 2 #The number of pods to be created in the Kubernetes cluster for the application container
  selector:
    matchLabels:
      app: python-app-service
  template:
    metadata:
      labels:
        app: python-app-service
    spec:
      containers:
        - name: python-app-service #The name of the application container
          image: merxxaz/python-app:v1.0.0 #The Docker image for building the application container
          ports:
            - containerPort: 8000 #The port for the application container